language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - cat schema.sql | mysql -utravis test
  - cat tests/dump.sql | mysql -utravis test

before_script:
  composer update --dev

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then php vendor/bin/coveralls -v; fi;'
